# Generated by Django 4.2.23 on 2025-08-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wechat',
            field=models.CharField(blank=True, max_length=50, verbose_name='微信号'),
        ),
    ]
