# Generated by Django 4.2.23 on 2025-08-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_userprofile_wechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True, verbose_name='HTML内容'),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_html',
            field=models.TextField(blank=True, verbose_name='HTML内容'),
        ),
    ]
